stages:
  - build

build:
  stage: build
  variables:
    MAVEN_OPTS: >-
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
    JAVA_HOME: /srv/jdk8u492-b09
  script:
    - echo $JAVA_HOME
    - mvn -V -B clean package
    - mvn -V -B compile jib:build -Dto.auth.username=$JIB_TO_AUTH_USERNAME -Dto.auth.password=$JIB_TO_AUTH_PASSWORD -DCI_PIPELINE_IID=$CI_PIPELINE_IID -P amd64
    - mvn -V -B compile jib:build -Dto.auth.username=$JIB_TO_AUTH_USERNAME -Dto.auth.password=$JIB_TO_AUTH_PASSWORD -DCI_PIPELINE_IID=$CI_PIPELINE_IID -P arm64
    - mvn -V -B compile jib:build -Dto.auth.username=$JIB_TO_AUTH_USERNAME -Dto.auth.password=$JIB_TO_AUTH_PASSWORD -DCI_PIPELINE_IID=$CI_PIPELINE_IID -P loong64
    - VERSION=$(mvn -B help:evaluate -Dexpression=project.version -q -DforceStdout)
    - TO_IMAGE=$(mvn -B help:evaluate -Dexpression=to.image -q -DforceStdout)
    - docker login --username $JIB_TO_AUTH_USERNAME --password $JIB_TO_AUTH_PASSWORD registry.cn-qingdao.aliyuncs.com
    - docker manifest create $TO_IMAGE:$VERSION $TO_IMAGE:$VERSION-amd64 $TO_IMAGE:$VERSION-arm64 $TO_IMAGE:$VERSION-loong64
    - docker manifest push $TO_IMAGE:$VERSION
    - docker manifest create $TO_IMAGE:$VERSION-$CI_PIPELINE_IID $TO_IMAGE:$VERSION-$CI_PIPELINE_IID-amd64 $TO_IMAGE:$VERSION-$CI_PIPELINE_IID-arm64 $TO_IMAGE:$VERSION-$CI_PIPELINE_IID-loong64
    - docker manifest push $TO_IMAGE:$VERSION-$CI_PIPELINE_IID
  cache:
    key: "${CI_JOB_NAME}-${CI_COMMIT_BRANCH}"
    paths:
      - .m2/repository
  tags:
    - shell
